name: "Publish and Release"
on:
    push:
        branches:
          - master
jobs:
    build-and-deploy:
        runs-on: ubuntu-lastest
        steps:
            - name: 检查master分支
              uses: actions/checkout@master
      
            - name: 安装依赖
              run: npm install
            
            - name: 构建packages
              run: npm run lib
